version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
      - export BUCKET=app2artifactucket
      - cloudguard fsp add -t f98c1ea5-e3dd-4d2e-80de-a779d37c87e1:wyisonz8b44fsrmdscwp7sui -C template.yaml --region us-east-1 --output template1.yaml
      - aws cloudformation package --template-file template1.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
      - 
artifacts:
  type: zip
  files:
    - template1.yaml
    - outputtemplate.yaml